### ISSUE TITLE
AssertionError - AlexNet Caffemodel

### ISSUE THREAD

**Issue by ChetanArvindPatil** [nilboy/extract-caffe-params#2]
Hi Xia,

I am using your python parser for caffemodel. However, I run into following issue: 

I0208 23:29:19.620373 42087 net.cpp:437] conv4 needs backward computation.
I0208 23:29:19.620442 42087 net.cpp:437] relu3 needs backward computation.
I0208 23:29:19.620515 42087 net.cpp:437] conv3 needs backward computation.
I0208 23:29:19.620591 42087 net.cpp:437] pool2 needs backward computation.
I0208 23:29:19.620656 42087 net.cpp:437] norm2 needs backward computation.
I0208 23:29:19.620725 42087 net.cpp:437] relu2 needs backward computation.
I0208 23:29:19.620793 42087 net.cpp:437] conv2 needs backward computation.
I0208 23:29:19.620863 42087 net.cpp:437] pool1 needs backward computation.
I0208 23:29:19.620964 42087 net.cpp:437] norm1 needs backward computation.
I0208 23:29:19.621076 42087 net.cpp:437] relu1 needs backward computation.
I0208 23:29:19.621137 42087 net.cpp:437] conv1 needs backward computation.
I0208 23:29:19.621201 42087 net.cpp:439] label_data_1_split does not need backward computation.
I0208 23:29:19.621268 42087 net.cpp:439] data does not need backward computation.
I0208 23:29:19.621330 42087 net.cpp:481] This network produces output accuracy
I0208 23:29:19.621392 42087 net.cpp:481] This network produces output loss
I0208 23:29:19.621491 42087 net.cpp:521] Network initialization done.
convert layer: conv1
Traceback (most recent call last):
  File "extract.py", line 36, in <module>
    extract_caffe_model(args.model, args.weights, args.output)
  File "extract.py", line 27, in extract_caffe_model
    np.save(output_path + '/' + str(name) + '_' + str(num), p.data)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 511, in save
    pickle_kwargs=pickle_kwargs)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 562, in write_array
    version)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 308, in _write_array_header
    header = asbytes(_filter_header(header))
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 467, in _filter_header
    return tokenize.untokenize(tokens)
  File "/usr/lib64/python2.7/tokenize.py", line 262, in untokenize
    return ut.untokenize(iterable)
  File "/usr/lib64/python2.7/tokenize.py", line 198, in untokenize
    self.add_whitespace(start)
  File "/usr/lib64/python2.7/tokenize.py", line 187, in add_whitespace
    assert row <= self.prev_row

Network is AlexNet. Would you be able to help me why this may be occuring?

**Comment by ChetanArvindPatil** [comment]
I solved the issue by downgrading `numpy `to `1.13.3`

`pip install numpy==1.13.3`
